name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nestaway-frontend:latest
      - name: ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker image prune
            cd /opt/nestaway
            docker compose stop
            docker compose up -d --pull always

            # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nestaway-frontend
            # docker stop nestaway || true
            # docker rm nestaway || true
            # docker run -d --name nestaway-frontend -p 80:5173 ${{ secrets.DOCKERHUB_USERNAME }}/nestaway-frontend
